// <auto-generated />
using System;
using FootballChampionship;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballChampionship.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballChampionship.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MatchId = 1,
                            Minute = 30,
                            PlayerId = 3
                        },
                        new
                        {
                            Id = 2,
                            MatchId = 1,
                            Minute = 45,
                            PlayerId = 4
                        },
                        new
                        {
                            Id = 3,
                            MatchId = 2,
                            Minute = 50,
                            PlayerId = 1
                        },
                        new
                        {
                            Id = 4,
                            MatchId = 2,
                            Minute = 75,
                            PlayerId = 2
                        },
                        new
                        {
                            Id = 5,
                            MatchId = 3,
                            Minute = 60,
                            PlayerId = 5
                        },
                        new
                        {
                            Id = 6,
                            MatchId = 3,
                            Minute = 80,
                            PlayerId = 6
                        },
                        new
                        {
                            Id = 7,
                            MatchId = 4,
                            Minute = 20,
                            PlayerId = 7
                        },
                        new
                        {
                            Id = 8,
                            MatchId = 4,
                            Minute = 90,
                            PlayerId = 8
                        });
                });

            modelBuilder.Entity("FootballChampionship.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "England",
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Spain",
                            Name = "La Liga"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Germany",
                            Name = "Bundesliga"
                        });
                });

            modelBuilder.Entity("FootballChampionship.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = 1,
                            AwayTeamId = 2,
                            HomeScore = 2,
                            HomeTeamId = 1,
                            LeagueId = 1,
                            MatchDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = 2,
                            AwayTeamId = 4,
                            HomeScore = 3,
                            HomeTeamId = 3,
                            LeagueId = 2,
                            MatchDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = 1,
                            AwayTeamId = 6,
                            HomeScore = 1,
                            HomeTeamId = 5,
                            LeagueId = 3,
                            MatchDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = 3,
                            AwayTeamId = 8,
                            HomeScore = 4,
                            HomeTeamId = 7,
                            LeagueId = 4,
                            MatchDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FootballChampionship.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 39,
                            Name = "Cristiano Ronaldo",
                            Nationality = "Portugal",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 2,
                            Age = 36,
                            Name = "Lionel Messi",
                            Nationality = "Argentina",
                            Position = "Forward",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            Name = "Bruno Fernandes",
                            Nationality = "Portugal",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            Name = "Virgil van Dijk",
                            Nationality = "Netherlands",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 30,
                            Name = "Paulo Dybala",
                            Nationality = "Argentina",
                            Position = "Forward",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            Age = 42,
                            Name = "Zlatan Ibrahimovic",
                            Nationality = "Sweden",
                            Position = "Forward",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 7,
                            Age = 35,
                            Name = "Robert Lewandowski",
                            Nationality = "Poland",
                            Position = "Forward",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            Name = "Erling Haaland",
                            Nationality = "Norway",
                            Position = "Forward",
                            TeamId = 8
                        });
                });

            modelBuilder.Entity("FootballChampionship.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundedYear = 1878,
                            LeagueId = 1,
                            Name = "Manchester United",
                            Stadium = "Old Trafford"
                        },
                        new
                        {
                            Id = 2,
                            FoundedYear = 1892,
                            LeagueId = 1,
                            Name = "Liverpool",
                            Stadium = "Anfield"
                        },
                        new
                        {
                            Id = 3,
                            FoundedYear = 1902,
                            LeagueId = 2,
                            Name = "Real Madrid",
                            Stadium = "Santiago Bernabéu"
                        },
                        new
                        {
                            Id = 4,
                            FoundedYear = 1899,
                            LeagueId = 2,
                            Name = "Barcelona",
                            Stadium = "Camp Nou"
                        },
                        new
                        {
                            Id = 5,
                            FoundedYear = 1897,
                            LeagueId = 3,
                            Name = "Juventus",
                            Stadium = "Allianz Stadium"
                        },
                        new
                        {
                            Id = 6,
                            FoundedYear = 1899,
                            LeagueId = 3,
                            Name = "AC Milan",
                            Stadium = "San Siro"
                        },
                        new
                        {
                            Id = 7,
                            FoundedYear = 1900,
                            LeagueId = 4,
                            Name = "Bayern Munich",
                            Stadium = "Allianz Arena"
                        },
                        new
                        {
                            Id = 8,
                            FoundedYear = 1909,
                            LeagueId = 4,
                            Name = "Borussia Dortmund",
                            Stadium = "Signal Iduna Park"
                        });
                });

            modelBuilder.Entity("FootballChampionship.Goal", b =>
                {
                    b.HasOne("FootballChampionship.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballChampionship.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballChampionship.Match", b =>
                {
                    b.HasOne("FootballChampionship.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballChampionship.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballChampionship.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballChampionship.Player", b =>
                {
                    b.HasOne("FootballChampionship.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballChampionship.Team", b =>
                {
                    b.HasOne("FootballChampionship.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballChampionship.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballChampionship.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
