// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewEntityFramework;

#nullable disable

namespace NewEntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewEntityFramework.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("NewEntityFramework.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Jeans",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Jacket",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Novel",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Cookbook",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Comics",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "Blender",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Microwave",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Vacuum Cleaner",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Board Game",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Name = "Action Figure",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Name = "Puzzle",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Name = "Football",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "Basketball",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Name = "Tennis Racket",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Name = "Camera",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Name = "Smartwatch",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Name = "Socks",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Name = "Sneakers",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Fantasy Novel",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Name = "Cookware Set",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Name = "Plush Toy",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Name = "Outdoor Tent",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Name = "Portable Speaker",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Name = "Winter Coat",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Name = "Comic Book",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Name = "Coffee Maker",
                            Price = 59.99m
                        });
                });

            modelBuilder.Entity("NewEntityFramework.Product", b =>
                {
                    b.HasOne("NewEntityFramework.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewEntityFramework.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
