// <auto-generated />
using System;
using Market;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Market.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250318084212_Customer-table")]
    partial class Customertable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Market.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FullName = "Alice Johnson",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FullName = "Bob Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            FullName = "Charlie Davis",
                            PhoneNumber = "555-666-7777"
                        },
                        new
                        {
                            Id = 4,
                            Email = "diana@example.com",
                            FullName = "Diana Roberts",
                            PhoneNumber = "444-555-6666"
                        },
                        new
                        {
                            Id = 5,
                            Email = "edward@example.com",
                            FullName = "Edward Clark",
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 6,
                            Email = "fiona@example.com",
                            FullName = "Fiona Martinez",
                            PhoneNumber = "888-999-0000"
                        });
                });

            modelBuilder.Entity("Market.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(6535),
                            TotalAmount = 1200.99m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7021),
                            TotalAmount = 699.50m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7022),
                            TotalAmount = 499.99m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7023),
                            TotalAmount = 199.99m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7024),
                            TotalAmount = 249.99m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7171),
                            TotalAmount = 299.99m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7172),
                            TotalAmount = 89.99m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7173),
                            TotalAmount = 49.99m
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 3,
                            OrderDate = new DateTime(2025, 3, 18, 8, 42, 11, 592, DateTimeKind.Utc).AddTicks(7174),
                            TotalAmount = 159.99m
                        });
                });

            modelBuilder.Entity("Market.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 10,
                            Name = "Laptop",
                            Price = 1200.99m
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 20,
                            Name = "Smartphone",
                            Price = 699.50m
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 50,
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 15,
                            Name = "Tablet",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 30,
                            Name = "Smartwatch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 25,
                            Name = "Monitor",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 40,
                            Name = "Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 60,
                            Name = "Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 12,
                            Name = "Printer",
                            Price = 159.99m
                        });
                });

            modelBuilder.Entity("Market.Order", b =>
                {
                    b.HasOne("Market.Customer", "Customers")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Market.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
